language: ruby
cache: bundler
bundler_args: --without benchmarks console tools
script: "bundle exec rake ci"
after_success:
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - jruby-9.2.7.0
  - truffleruby
matrix:
  allow_failures:
    - rvm: truffleruby
    - rvm: jruby-9.2.7.0
env:
  global:
    - COVERAGE='true'
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
